// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6N6ILgcDpn2EY3fh7ns13QfkBRdjsoaU',
    appId: '1:586847000074:android:c82f78c098f9890b65b1f3',
    messagingSenderId: '586847000074',
    projectId: 'encarte-facil',
    storageBucket: 'encarte-facil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrfwlmzWEryfqYwIhVqF75l4jM-RiBdOg',
    appId: '1:586847000074:ios:8bc40cd1a41fe1b065b1f3',
    messagingSenderId: '586847000074',
    projectId: 'encarte-facil',
    storageBucket: 'encarte-facil.appspot.com',
    iosClientId: '586847000074-3vfbt8agq16ja6vapomk46mluv7nul1u.apps.googleusercontent.com',
    iosBundleId: 'com.marcelo.encarteFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrfwlmzWEryfqYwIhVqF75l4jM-RiBdOg',
    appId: '1:586847000074:ios:3f8ec87830e8cf3565b1f3',
    messagingSenderId: '586847000074',
    projectId: 'encarte-facil',
    storageBucket: 'encarte-facil.appspot.com',
    iosClientId: '586847000074-1r55jnrokjqbuesqaqodid435vslt2ag.apps.googleusercontent.com',
    iosBundleId: 'com.marcelo.encarteFacil2',
  );
}
